### ISSUE TITLE
Issues with gpd xd plus, glitchy graphics

### ISSUE THREAD

**Issue by skelton** [devmiyax/yabause#484] opened 2017-12-31 11:36 UTC
I am testing right now a New xd plus, which use a mtk 8176. It uses a power vr gx6250, It Supports OpenGL 3.2 and vullkan with Android 7. However, though performance is very good, most games have rendering issues. I suppose because of powervr drivers. Is there anything i can try to debug the device and provide a better feedback? I can try to post screeshot but each Game has a different issue, so not sure if can be helpful or not

**Comment by devmiyax** [comment] 2018-01-01 20:13
Oh.. I love GPD XD. I want to fix this issue. How can I obtain GPD XD Plus?

**Comment by skelton** [comment] 2018-01-01 20:22
Hi. Device Will be on sale in february/march. I am testing it. If you want to get one, try Contact samty@softwincn.com. tell them you want to fix taba sanshiro for XD plus and that you know me and they perhaps can send you one. I am the author of legacyrom for XD by the way. Xd plus is similar to xd, but with mtk8176, like xioami mi pad 3, 4 GB RAM, android nougat and bluetooth.

**Comment by skelton** [comment] 2018-01-17 17:49
Any way to provide you a logact to see into the isse in gpd xd plus? Strangely xiaomi mi pad3 doesn't have those issues with same GPU (older drivers in xiaomi it seems, because xiaomi mi pad 3 still don't suppport vukan) If there is a way I can debug a logact for you let me know.

**Comment by devmiyax** [comment] 2018-01-21 07:26
I've obtained Fire HD 10 which also has gx6250 and I understand the issue.

![image](https://user-images.githubusercontent.com/1174152/35191795-af455984-fec7-11e7-910e-4b01f38e7ccc.png)

**Comment by devmiyax** [comment] 2018-01-21 07:33
In my experience, this issue is caused by the fault of rendering synchronization in GPU driver. I can't beleive that there is a bug in such a basic function. I guess that's why they are fired from Apple.

**Comment by skelton** [comment] 2018-01-21 08:14
Thanks for the testiing. Yeah, certainly it seems gpu drivers are not great. Thanks for your work trying to fix it.

**Comment by devmiyax** [comment] 2018-02-06 16:06
I've obtained GPD XD+. and I ask Imagination technology guy how to solve this problem here. https://community.imgtec.com/forums/topic/eglswapbuffers-displays-before-rendering-has-finished/

They say they need PVRTrace result. But to use PVRTrace root permission is needed.

Do you how I can be root on GPD XD+?

**Comment by skelton** [comment] 2018-02-06 16:29
You need to enter settings, developee options And Enable the oem Enable
option to unlock bootloader. After that install magisk manager And place
boot.img from firmware into internal memory so magisk can patch It. Once
patched you need to flash new boot.img with so flash tools, the tool to
flash Mtk images. Firmware link is here,
https://mega.nz/#!MygmVLgQ!msVqelPNw1wtGvSBk3lkKsuKE9YQR3Dl5HfI5pAN4bw

**Comment by sorianouk** [comment] 2018-02-07 12:54
im running a gdp xd 32bit ver,  the emulator for the most part does seem very promising for this platform if its running on legacy fw.  however i am currently using an older yabause build (pre san shiro) as it runs more titles than current builds.  im currently testing the latest build with a list of titles and will give feedback based on this particular device.

**Comment by devmiyax** [comment] 2018-02-09 02:05
I've written boot.img. but still, I can not use su command. Can you help?

![image](https://user-images.githubusercontent.com/1174152/36007994-68acc5f0-0d88-11e8-925b-19e53b817391.png)

**Comment by skelton** [comment] 2018-02-09 09:25
Did you flash your patched boot.img and installed magisk manager? In that
case adb or terminal should ask you for root permission in magisk, Did you
try root checker to se if you rooted it right?

2018-02-09 3:05 GMT+01:00 devmiyax <notifications@github.com>:

**Comment by devmiyax** [comment] 2018-02-09 21:28
I managed to obtain the root permission with this setting. Thank for your help. 

![image](https://user-images.githubusercontent.com/1174152/36050827-57d64528-0e2b-11e8-86ca-9bdf9877d6fe.png)

**Comment by Black-Seraph** [comment] 2018-07-02 12:44
Has there been any progress made on this front?
If not, is there a way the GPD community, myself on the forefront, can help you @devmiyax?

**Comment by devmiyax** [comment] 2018-07-05 13:23
@Black-Seraph  Do you obtain the new driver which fixes this bug?

**Comment by devmiyax** [comment] 2019-10-04 22:58
https://forums.imgtec.com/t/eglswapbuffers-displays-before-rendering-has-finished/2575/14

**Comment by Cwiiis** [comment] 2019-10-05 21:10
I think the most sensible way forward for this would be to experiment and find a viable work-around, if one exists - I very much doubt we'll see a more recent driver with the fixed problem and I assume the Vulkan backend isn't a near-term project. I'm just trying to get an Android dev environment setup so I can experiment on my device.

**Comment by Cwiiis** [comment] 2019-10-05 22:57
Got it building, just need to figure out how to generate the apk now... Submitted a PR to fix some build issues I experienced: https://github.com/devmiyax/yabause/pull/648

**Comment by Cwiiis** [comment] 2019-10-05 23:43
Great, got a setup where I can build and test on device now, so fingers crossed I can find some work-around. If I discover anything interesting I'll report back.

**Comment by Cwiiis** [comment] 2019-10-06 13:12
I'm having a hard time isolating exactly what this issue is - I assumed at first that it's a concurrency issue with some buffer swap at some point happening while rendering is still happening (which the discussion on this bug and the Imagination forum thread suggests)... But disabling all async rendering and putting a pretty generous wait before eglSwapBuffers seems to exacerbate the problem if anything. I've tried various areas to put in waits/glFinish's and I've not managed to find any kind of consistent thing that helps or hinders. This is after disabling all threaded rendering too.

The weirdest thing is I just can't isolate exactly what it is that causes the issue to manifest. I'm using Shining the Holy Ark to test. The opening sequences always render fine and the bug manifests only once the first dialog box appears after the title sequence, which corresponds to when VDP1 and RBG0 (and NBG2 and 3) are simultaneously visible... The problem doesn't go away when I disable RBG0 rendering, but it does still occur at the same place, but I'm not really sure what that tells me yet.

**Comment by Cwiiis** [comment] 2019-10-06 13:42
Interestingly, all artifacts disappear if I disable NBG rendering by commenting out the calls to Vdp2DrawNBG* in vidogl.c. I'm going to take a look at what's happening inside those functions next...

**Comment by Cwiiis** [comment] 2019-10-06 15:04
I've isolated it down to the last part of Vdp2DrawPatternPos - something happening in Vdp2DrawCell, possibly, is causing this issue to manifest. Disabling the cache has no discernible effect. Returning before the call to YglQuadOffset means the issue won't manifest. Still digging, but I'm hopeful a work-around is possible...

**Comment by Cwiiis** [comment] 2019-10-06 15:13
If anything, the problem is exacerbated by disabling the cache, which makes me think it's something to do with the allocation in YglQuadOffset that's triggering the issue... Going to play around with that for a bit, see if I can narrow it down some more.

**Comment by Black-Seraph** [comment] 2019-10-06 15:23
Keep us posted.

If you can nail this down to a specific driver API call then I can build a wrapper library we can pull on top of the afflicted driver to patch this out in the OS.

**Comment by Cwiiis** [comment] 2019-10-06 15:43
This is happening when the sprite atlas for NBG drawing is allocated/reallocated, but I haven't pinned down what exactly about that the problem is or how to isolate it. Even if you just allow the allocations to happen but never actually write any data into the texture, the issue happens - so something about the allocation or the churning of allocation is causing this. I don't know that this can be worked around by patching an API call (but I can't rule it out just yet - seems unlikely though).

I expect we may be able to work around this by pre-allocating the sprite atlas texture, and making it a size that means that reallocation will never need to happen. I'm still investigating to know if this is the case or not though. Possibly there may be other work-arounds here, like changing some particular parameter somewhere, or perhaps only allocating power-of-two size textures or the like - this is pure conjecture, mind. Hopefuly I'll find something.

**Comment by Cwiiis** [comment] 2019-10-06 16:18
Still trying to wrap my head around how things work, but it kind of looks like there are two texture managers - one that's global that gets used for both VDP2 sprites and the screen buffers, and another for VDP1 rendering. The VDP1 manager allocates at a size where reallocations don't happen, so this is fine (I think?). This bug seems to be that reallocating the texture in the screen/VDP2 manager doesn't synchronise correctly, so during that reallocation, partial rendering gets shown.

I think a suggestion to fix it would be to over-allocate the VDP2/screen texture by default so the reallocation can't happen, or to allow it to grow without shrinking it so you may occasionally see a few glitchy frames but it would iron itself out over a run (and probably be a net performance win even on devices that don't suffer from this bug?) I don't know that this understanding is correct, but it might also explain why this bug seems to be highly dependent on the resolutions picked, as higher resolutions are less likely to cause reallocations and the reallocation may be slow enough or hit some uncached path in the driver that causes a flush. Doing this may not be as simple as it sounds, but going to give it a shot.

**Comment by Cwiiis** [comment] 2019-10-06 19:50
My suggested work-around works, but I haven't found a good way of integrating it yet (but it shouldn't be difficult, I think...)

Essentially, if you add something along the lines of:

`if (width < 4096) width = 4096;
if (height < 4096) height = 4096;`

at the top of `YglTMRealloc`, though you will still see some glitching occasionally (which I guess is due to the allocation still being done on-demand every frame, rather than just once), it will mostly be fine. This buffer still appears to be reallocated every frame and I haven't figured out how to get that not to happen yet, but I'm working on it...

This does appear to be a driver bug, but I think the emulator's behaviour here is somewhat pathological. Re-allocating textures in this way is likely quite inefficient, and given the general quality of drivers on Android, I'm unsurprised that it's uncovered an issue. I would suggest at least, that the allocation size should increase logarithmically so as not to cause allocation churn/memory fragmentation, and that it shouldn't be discarded and reallocated every frame.

**Comment by Cwiiis** [comment] 2019-10-06 19:59
Unfortunately, this doesn't appear to work if I re-enable asynchronous rendering, however :( I'll need to do more digging...

**Comment by Black-Seraph** [comment] 2019-10-06 20:16
I applaud your work so far. I wish we could get some feedback from Alldocube X tablet owners on this issue as they've got the 1.9 PowerVR rogue driver already.

**Comment by Cwiiis** [comment] 2019-10-07 02:51
I missed some code, it does look like VDP1 and 2 share the same texture manager actually and the screen's texture manager isn't touched - this is good, it should be easier to do what I suggested given this. The problem's cause is still the same and I'm hoping the fix doesn't work because it still does reallocation mid-frame, so I'm going to press ahead with that possible solution and hope it still fixes things even with async rendering enabled.

**Comment by Cwiiis** [comment] 2019-10-07 02:52
> I applaud your work so far. I wish we could get some feedback from Alldocube X tablet owners on this issue as they've got the 1.9 PowerVR rogue driver already.

It's a shame this tablet is quite expensive... If it was in the sub-£100 range, I'd be pretty tempted to get it and find out! I'm guessing the video driver isn't trivially compatible with the XD+?

**Comment by Black-Seraph** [comment] 2019-10-07 03:05
The issue is that for the 1.9 driver to work I first need to port Treble to the XD+ (which is an on-going effort of mine).

Most of the Alldocube drivers work fine on the XD+ (except the lcm of course as they are for different panels), but getting the few that don't to play nice is a pain.

I just wish we could ask someone that has the actual tablet to see if the 1.9 PowerVR rogue driver actually fixes this issue.

**Comment by Cwiiis** [comment] 2019-10-07 03:18
So debugging things on the Linux build, I had completely misread the situation and the texture manager *does* work as I suggested - it starts at 512x512 and reallocate is only called if it needs to grow... Which makes me wonder why adding the change to reallocate that I did did anything at all on device, as reallocate doesn't actually seem to get called at all (for Shining the Holy Ark at least)... Unless it's behaving differently on the Android build for some reason... Curious! Disabling NBG drawing does fix this, so something that's happening in that path is triggering this issue... I thought it was the texture reallocation, but perhaps it's something else...

**Comment by Cwiiis** [comment] 2019-10-07 04:43
Ok, so ignoring my bad assumptions earlier, the issue seems to be triggered by one of the drawing programs used by YglQuadOffset - if you disable its drawing by commenting out the line `program->currentQuad += 12;`, this does everything except the final drawing and the issue doesn't manifest. I think/hope this is a nice find, as disabling it in this way still does all the atlas allocation/writing/mapping, it just skips the final drawing. I think.

**Comment by Cwiiis** [comment] 2019-10-07 05:07
Another odd discovery, the same shader that's used to draw RBG0 is the one used to draw NBG, setup by `YglQuadOffset` - drawing RBG0 is fine and has no issues... As far as I can tell, `YglQuadOffset` and `YglQuadRbg0` are nearly identical in terms of the parameters they setup, but I'll be investigating the difference between them. Possibly this bug is just triggered by the extra work this setups, but I'm hoping there's something here that can be isolated and fixed/worked around...

**Comment by Cwiiis** [comment] 2019-10-07 05:47
If I disable the drawing by just calling discard in the pixel shader of normal CRAM drawing, the issue doesn't manifest - which is starting to make me think that a work-around would need to be a bit more involved than I would've hoped for... I'd really like to pinpoint why this path works for RBG0 but not for NBG.

What's weird/interesting, is I've discovered a sequence of events that seems to 'fix' the issue, in my checkout at least, but I'm guessing it's just a lucky coincidence. I have discovered what I think may be a few unrelated issues in this code-path, but none that relate to this.

**Comment by Cwiiis** [comment] 2019-10-07 06:59
After experimenting a bit, the bug is triggered only when a texel read happens via setup from YglQuadOffset (which is only called by the DrawpMap functions, which are in turn only called by the Vdp2DrawNBG functions). I still don't know what's special about these particular reads vs. the reads triggered by RBG0. I rigged things to do everything *except* write the CRAM data to the texture, to see what happens then, and indeed the bug is still triggerred... Quite intriguing... I'm going to leave this for now (work!) but I'll continue in my spare time and report anything interesting.

**Comment by Chine79** [comment] 2020-04-27 16:47
Well, anything new?

**Comment by Cwiiis** [comment] 2020-04-27 16:54
Not on my end at least - I think the last comment I made would be a great clue to follow up for someone more familiar with how Yaba renders (so really, just @devmiyax). I'd love to see this fixed, for sure, but I don't think I have the time to dig deeper right now.

I'm not *entirely* convinced this is a driver bug vs. undefined behaviour from lack of synchronisation in drawing (and just the majority of drivers being ok with it). It may well be, I'm just not completely sure. It's intriguing that no amount of flushing and usleep changes how this bug manifests (iirc).

**Comment by Black-Seraph** [comment] 2020-09-20 15:35
> I'd be more inclined to look into this if I knew that me fixing it would result in my commits being in the repo, but last time I fixed something, my work was copied without attribution.
If a emulator-side implementation isn't to your liking, feel free to get in touch with me for a OS / driver-sided fix.
If we can isolate the exact API call that busts us, we would have a good starting point to start digging in the kernel driver sourcecode.

**Comment by wataru-jack** [comment] 2020-11-28 15:38
Hi everyone. I found a tentative solution to this problem.

GPD XD+
Android version 9 (lineageos)

Yaba sanshiro 2 
Version 1.1.0
Almost settings as default. I changed only Cpu Core to 'Interpreter'

How to fix it
1. Startup game
2. Change setting to 'Use Compute Shader' on
3. Back to game
4. Change setting to 'Use Compute Shader' off 

Repeat 2-4 several times, there is a timing when the polygon will be displayed normally.
Once it is displayed normally, I can play without breaking the display.

I shot a video and uploaded it.
https://youtu.be/JsmNBL9vDkU

**Comment by Black-Seraph** [comment] 2021-05-31 18:26
This issue can be closed as I've FINALLY resolved it on my latest build of LineageOS 18.1 (Beta 18) for the XD+ (it can be found over at my Patreon https://patreon.com/blackseraph starting June 4th).

For those that wonder: The issue was a driver issue, yes... the first driver to contain the required change is the PowerVR Rogue RGX 1.9 driver... and it needs two driver settings overridden in the /vendor/etc/powervr.ini file.

Namely: DisableFBCDC=1 and DefaultVertexBufferSize=819200

Given that only one MT8173/8176 device out there ever received the 1.9 driver update officially (the Alldocube X tablet), this means that only MT8173/8176 devices that have an unofficial port of the driver (like my LineageOS beta builds for XD+) can ever hope of fixing this... Hell, even the Alldocube X tablet needs these two settings slipstreamed in via root before working properly, as these two aren't set by default.

Theoretically, the new 1.9 driver could be ported to the Mi Pad 3 just the same way I ported it to the XD+, which means that, with enough effort, this could be fixed by a dedicated ROM maker like myself. I do however not have a Mi Pad 3, so this task will be left for someone else now that I've shared the essential bits.

Here's a link to a YouTube video showing off the fix: https://www.youtube.com/watch?v=BHMnf2INd-s

**Comment by Cwiiis** [comment] 2021-05-31 18:54
> This issue can be closed as I've FINALLY resolved it on my latest build of LineageOS 18.1 (Beta 18) for the XD+ (it can be found over at my Patreon https://patreon.com/blackseraph starting June 4th).
> 
> For those that wonder: The issue was a driver issue, yes... the first driver to contain the required change is the PowerVR Rogue RGX 1.9 driver... and it needs two driver settings overridden in the /vendor/etc/powervr.ini file.
> 
> Namely: DisableFBCDC=1 and DefaultVertexBufferSize=819200
> 
> Given that only one MT8173/8176 device out there ever received the 1.9 driver update officially (the Alldocube X tablet), this means that only MT8173/8176 devices that have an unofficial port of the driver (like my LineageOS beta builds for XD+) can ever hope of fixing this... Hell, even the Alldocube X tablet needs these two settings slipstreamed in via root before working properly, as these two aren't set by default.
> 
> Theoretically, the new 1.9 driver could be ported to the Mi Pad 3 just the same way I ported it to the XD+, which means that, with enough effort, this could be fixed by a dedicated ROM maker like myself. I do however not have a Mi Pad 3, so this task will be left for someone else now that I've shared the essential bits.
> 
> Here's a link to a YouTube video showing off the fix: https://www.youtube.com/watch?v=BHMnf2INd-s

Amazing work, almost makes me wish I hadn't sold my XD+ now!

I suspect that those settings are actually papering over a deeper issue, possible in Yaba - I'm guessing the DC in FBCDC stands for DirectCopy, and I expect disabling that and raising the vertex buffer size is working around a threading issue that's causing some memory to get stomped while it's still being used. Possibly other drivers work in different ways or have more safe-guards/locking that the issue doesn't show up there. May well just be a driver issue, but I'm very suspicious of the threading code in Yaba's GL renderer...

**Comment by devmiyax** [comment] 2021-06-01 22:32
AWESOME! I want to try ASAP.

**Comment by Black-Seraph** [comment] 2021-06-02 11:09
Anything else you need, info-wise to close this issue? Technically this issue references the XD Plus specifically... and given that the issue is now fixed on the XD Plus after figuring out that a driver in need of repair was the cause, what else is there to contribute?

This does affect every PowerVR GX6250 equally though (in fact, every Rogue-type PowerVR GPU, of which there are 3 I think...?), so maybe it would make sense to let the issue stay but rename it accordingly?

Pondering here, but there's also the question of whether we can use other PowerVR blobs / kernel drivers of the same archetype within the same family of products... because there is a clyde-type PowerVR 1.10 driver out in the wild that is a good year younger than the 1.9 one I pilfered from the Alldocube X tablet to use as my base... will the fix I found still be necessary when using that driver if it can be adapted?

**Comment by devmiyax** [comment] 2022-04-09 08:27
no more PowerVR nowadays.

**Closed by devmiyax** 2022-04-09 08:27 UTC
Labels: Graphics
