### ISSUE TITLE
DRACULA-X                                                                                                       

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#528] opened 2018-04-12 23:04 UTC
version:1.6.5
device:SHIELD Android TV
cpu_type:3
video_type:1
comment:
[state file](http://www.uoyabause.org//system/reports/state_files/000/003/564/original/T-9527G_2018_03_10_00_52_42.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/003/564/original/screenshot.png?1520671971)

**Comment by fivefeet8** [comment] 2018-04-13 15:57
This is a duplicate of my issue ticket.

**Comment by fivefeet8** [comment] 2018-04-28 06:39
Fixed in 1.8

**Closed** 2018-05-05 00:15 UTC
